sudo : required

services:
  - docker

script:
  - docker build -t codebase ./codebase
  - docker build -t app ./app
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push $DOCKER_ID/codebase
  - docker push $DOCKER_ID/app
